### ISSUE TITLE
NPE spotted in mediator logs

### ISSUE THREAD

**Issue by BarDweller** [gameontext/gameon-mediator#87]
```
[3/8/18 12:55:20:884 UTC] 0001abef id=         org.gameontext.mediator                                      I : ae611df2 : C    M <- R : player,*,{"type":"chat","username":"The ugly monster","content":"I am still alive!","bookmark":"not-bookmarked"}
[3/8/18 12:55:20:884 UTC] 0001abef id=         org.gameontext.mediator                                      W : 815ed5c4 : Uncaught exception handling client-bound message
java.lang.NullPointerException
	at org.gameontext.mediator.MediatorNexus$SingleUserView.stillConnected(MediatorNexus.java:669)
	at org.gameontext.mediator.MediatorNexus$SingleUserView.sendToClients(MediatorNexus.java:660)
	at org.gameontext.mediator.room.WebSocketClientConnection$1.onMessage(WebSocketClientConnection.java:135)
	at org.gameontext.mediator.room.WebSocketClientConnection$1.onMessage(WebSocketClientConnection.java:125)
	at com.ibm.ws.wsoc.LinkRead.processWithWholeMessageHandler(LinkRead.java:639)
	at com.ibm.ws.wsoc.LinkRead.processRead(LinkRead.java:335)
	at com.ibm.ws.wsoc.WsocConnLink.processRead(WsocConnLink.java:990)
	at com.ibm.ws.wsoc.WsocReadCallback.completeLogic(WsocReadCallback.java:61)
	at com.ibm.ws.wsoc.WsocReadCallback.complete(WsocReadCallback.java:47)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)
```

**Comment by BarDweller** [comment]
Might be a dupe of #48 ?

**Comment by ebullient** [comment]
mediator          | [ERROR   ] CWWKH0039E: When an outgoing WebSocket request was sent to the ws://samplemicroservice.eu-gb.mybluemix.net/room endpoint on the target server, a Status code: 500 response was returned instead of a 101 response.
mediator          | [ERROR   ] CWWKC1101E: The task org.gameontext.mediator.room.RemoteRoom$$Lambda$32/00000000B401EE60@1a46d019, which was submitted to executor service managedScheduledExecutorService[DefaultManagedScheduledExecutorService], failed with the following error: java.lang.NullPointerException
mediator          | 	at org.gameontext.mediator.room.WebSocketClientConnection.keepAlive(WebSocketClientConnection.java:94)
mediator          | 	at org.gameontext.mediator.room.RemoteRoom.lambda$new$0(RemoteRoom.java:55)
mediator          | 	at org.gameontext.mediator.room.RemoteRoom$$Lambda$32/00000000B401EE60.run(Unknown Source)
mediator          | 	at com.ibm.ws.concurrent.internal.ScheduledTask.call(ScheduledTask.java:418)
mediator          | 	at [internal classes]
