### ISSUE TITLE
NPE in Mediator

### ISSUE THREAD

**Issue by ebullient** [gameontext/gameon-mediator#99]
```
mediator          | [ERROR   ] CWWKH0039E: When an outgoing WebSocket request was sent to the ws://samplemicroservice.eu-gb.mybluemix.net/room endpoint on the target server, a Status code: 500 response was returned instead of a 101 response.
mediator          | [ERROR   ] CWWKC1101E: The task org.gameontext.mediator.room.RemoteRoom$$Lambda$32/00000000B401EE60@1a46d019, which was submitted to executor service managedScheduledExecutorService[DefaultManagedScheduledExecutorService], failed with the following error: java.lang.NullPointerException
mediator          | 	at org.gameontext.mediator.room.WebSocketClientConnection.keepAlive(WebSocketClientConnection.java:94)
mediator          | 	at org.gameontext.mediator.room.RemoteRoom.lambda$new$0(RemoteRoom.java:55)
mediator          | 	at org.gameontext.mediator.room.RemoteRoom$$Lambda$32/00000000B401EE60.run(Unknown Source)
mediator          | 	at com.ibm.ws.concurrent.internal.ScheduledTask.call(ScheduledTask.java:418)
mediator          | 	at [internal classes]
```

**Comment by ebullient** [comment]
This could consume the other two outstanding NPE (#87 and #48) .. though these are room side
